---
title: "EDLD 650: Advanced Seminar in Educational Research Methods"
subtitle: "aka Methods for Causal Inference in Educational Research"


site: distill::distill_website
output:
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE)
```

# Course Overview

This course explores methods for causal inference in educational research. The two primary goals of the course are (1) to provide students with the analytic tools and skills to assess the quality of research claims in education, human development, and other substantive fields; and (2) to provide students with the skills to conduct research that supports causal inference. The course will introduce students to three core methods of quasi-experimental design: difference-in-differences, instrumental variables and matching. Students will also advocate for and elect a fourth method to study such as regression discontinuity, comparative interrupted time series, or a deeper dive into one of the three planned methods. The course will culminate in either a research proposal or completed paper using one of the methods from the course. *Prior coursework minimally through multiple regression and familiarity with a statistical programming language (preferably R) is assumed.*

# Meeting time and location
Tuesdays, 9:00am - 11:50am
Lokey 119

# Instructor
David Liebowitz
